package taxon

var defaultCategories = []string{
	"Applications",
	"Nice!",
	"Kubernetes",
	"Docker",
	"External APIs",
	"General helpers",
	"Security",
	"Databases",
	"Clients",
	"Go Tools",
	"Docs and books",
	"Logging",
	"Other languages",
	"Protocols",
	"Deploy and Orchestration",
	"Graphics",
	"Containers",
	"HTTP",
	"Testing",
	"File Formats",
	"Distributed computing",
	"Web Framework",
	"Proxies",
	"Data structures",
	"SQL/ORM",
	"Terminal",
	"Microservices",
	"Gaming",
	"Performance",
	"System tools",
	"Local development",
	"HTTP middleware",
	"Monitoring and alerting",
	"JSON",
	"Machine Learning",
	"Auto Rebuild",
	"Command Line",
	"HTTP Clients",
	"Text Processing",
	"Message queue",
	"DNS",
	"Hardware",
	"Redis",
	"HTTP router",
	"Cryptocurrencies",
	"Filesystem",
	"ElasticSearch",
	"Process Management",
	"Templates",
	"Linux-related",
	"Mail",
	"Statsd",
	"UUID",
	"GUI",
	"SSH",
	"Search Engines",
	"Job queue",
	"Math",
	"Config",
	"Vendoring",
	"Validation",
	"Networking",
	"HTML",
	"Compression",
	"Bioinformatics",
	"Finance",
	"AMQP",
	"Bots",
	"Embedded Key-Value Store",
	"Cryptography",
	"Geo",
	"Assets",
	"File Storage",
	"Android",
	"BitTorrent",
	"Slack",
	"IRC",
	"RPC",
	"Cron",
	"Scrapers",
	"Crawlers",
	"Caching",
	"RSS",
	"Date and Time",
	"Audio",
	"Mac-related",
	"P2P",
	"BoltDB",
	"CUDA",
	"Resource pools",
	"Pretty Print",
	"Windows-related",
	"SOAP",
	"Micro Databases",
	"gRPC",
	"Server-sent events",
	"Markdown",
	"CQRS/ES",
	"Websockets",
	"Backup",
	"Debuggers",
	"I18n",
	"MQTT",
	"APNS",
	"Telegram",
	"Graph Algorithms",
	"Cuckoo Filter",
	"QR codes",
	"Admin Interfaces",
	"XLSX",
	"Recommendation engines",
	"DHCP",
	"RTSP",
	"PageRank",
	"Syntax Highlight",
	"Stripe",
	"Events",
	"CSS",
	"Virtualization",
	"Static Files / Bindata",
	"Serverless",
	"WHOIS",
	"Avro",
	"Sync",
	"OAuth",
	"PHP and Go",
	"JIRA",
	"RTMP",
	"PAAS",
	"MP4",
	"Fuzzy string matching",
	"CSV",
	"Video",
	"Image Manipulation",
	"Chaos Testing",
	"Monitoring",
	"Laravel",
	"MySQL",
	"Translations",
	"JSON-to-Struct",
	"Blockchain",
	"pHash",
	"Localization",
	"Amazon Web Services",
	"Go AltScene",
	"Jupyter",
	"PDF",
	"Dependency Injection",
	"Object Storage",
	"Reverse Proxy",
	"Annotation Processor",
	"E-Commerce",
	"BDD",
	"Spring",
	"Admin Interface",
	"Object Mapper",
	"Vault",
	"CoreDNS",
	"Dapper",
	"Log tailing",
	"Container Runtime",
	"Tensorflow",
	"Nginx",
	"Jenkins",
	"Data Science",
	"Route53",
	"Helm Charts",
	"Tutorials",
	"Music",
	"Envoy",
	"Blog",
	"Forum",
	"SEO",
	"Instagram",
	"Postmark",
	"Site Builder",
	"NLP",
	"ETL",
	"SSL",
	"SVG",
	"Typo3",
	"Azure",
	"Laravel e-Commerce",
	"Laravel Shopping Cart",
	"Slim framework",
	"Charts",
	"V2EX",
	"Text / String manipulation",
	"MongoDB",
	"CMS",
	"PHP language tools",
	"Symfony",
	"WordPress",
	"Syntax Highlighting",
	"IP filtering",
	"Fault tolerance",
	"Authorization",
	"WebRTC",
	"Breadcrumbs",
}
